export let ADD_TO_CART = 'CART/ADD_TO_CART';
export let DELETE_FROM_CART = 'CART/DELETE_FROM_CART';
export let DELIVERY_METHOD = 'CART/DELIVERY_METHOD';
export let PAYMENT_METHOD = 'CART/PAYMENT_METHOD';
export let ADDRESS = 'CART/ADDRESS';